### ISSUE TITLE
你好我有些细节想跟您聊一下可以吗

### ISSUE THREAD

**Issue by ztt0922** [emptysoal/tensorrt-experiment#1]

**Comment by emptysoal** [comment]
可以的

**Comment by ztt0922** [comment]
可以加您的联系方式吗，我对于deeplab里面一些操作有一些想法



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2023年8月15日(周二) 上午10:00
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [emptysoal/tensorrt-experiment] 你好我有些细节想跟您聊一下可以吗 (Issue #1)




 
可以的

**Comment by emptysoal** [comment]
好的，加我微信吧18811408518，我也是刚学习tensorrt，欢迎一起交流
